INSERT INTO products (name, price, description, product_storage_type_id) VALUES
    ('Canned Corn', 1.99, 'Sweet corn in a can, 15oz', 1),
    ('Pasta Spaghetti', 1.49, 'Traditional spaghetti pasta, 1lb', 1),
    ('Olive Oil', 8.99, 'Extra virgin olive oil, 500ml', 1),
    ('Rice - Long Grain', 4.99, 'White long grain rice, 2lb bag', 1),
    ('Canned Tuna', 2.49, 'Chunk light tuna in water, 5oz', 1),
    ('Peanut Butter', 3.99, 'Creamy peanut butter, 16oz jar', 1),
    ('Oatmeal', 3.49, 'Old fashioned rolled oats, 18oz', 1),
    ('Canned Tomatoes', 1.79, 'Diced tomatoes, 14.5oz can', 1),
    ('Flour - All Purpose', 2.99, 'All-purpose baking flour, 5lb', 1),
    ('Cereal - Corn Flakes', 3.29, 'Classic corn flakes cereal, 18oz', 1),
    ('Bananas', 0.59, 'Fresh yellow bananas, per lb', 2),
    ('Ground Beef', 5.99, '80/20 lean ground beef, 1lb', 2),
    ('Milk - Whole', 3.49, 'Fresh whole milk, 1 gallon', 2),
    ('Chicken Breast', 7.99, 'Boneless skinless chicken breast, per lb', 2),
    ('Salmon Fillet', 12.99, 'Fresh Atlantic salmon fillet, per lb', 2),
    ('Eggs', 2.99, 'Large grade A eggs, dozen', 2),
    ('Lettuce - Romaine', 2.49, 'Fresh romaine lettuce head', 2),
    ('Apples - Gala', 1.99, 'Fresh Gala apples, per lb', 2),
    ('Yogurt - Greek', 4.99, 'Plain Greek yogurt, 32oz', 2),
    ('Carrots', 1.29, 'Fresh whole carrots, 1lb bag', 2),
    ('Ice Cream - Vanilla', 4.99, 'Premium vanilla ice cream, 1 pint', 3),
    ('Frozen Pizza', 6.49, 'Pepperoni frozen pizza, 12 inch', 3),
    ('Frozen Vegetables', 2.99, 'Mixed frozen vegetables, 16oz bag', 3),
    ('Frozen Berries', 8.99, 'Mixed frozen berries, 2lb bag', 3),
    ('Frozen French Fries', 3.49, 'Crinkle cut frozen fries, 2lb bag', 3),
    ('Frozen Chicken Nuggets', 5.99, 'Breaded chicken nuggets, 2lb bag', 3),
    ('Frozen Fish Sticks', 4.79, 'Breaded fish sticks, 1lb box', 3),
    ('Frozen Waffles', 2.99, 'Homestyle frozen waffles, 10 count', 3),
    ('Frozen Orange Juice', 3.29, 'Concentrated orange juice, 12oz', 3),
    ('Ice Pops', 3.99, 'Assorted flavor ice pops, 18 count', 3);

