CREATE TABLE orders (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    total_cost DECIMAL(10,2) NOT NULL,
    order_time TIMESTAMP NOT NULL,
    delivery_date DATE NOT NULL,
    delivery_time TIME NOT NULL,
    is_green_delivery BOOLEAN NOT NULL,
    user_id INT NOT NULL REFERENCES users(id),
    customer_id INT NOT NULL REFERENCES customers(id)
);

