CREATE TABLE order_items (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cost_per_item DECIMAL(10,2) NOT NULL,
    quantity INT NOT NULL,
    product_id INT NOT NULL REFERENCES products(id),
    order_id INT NOT NULL REFERENCES orders(id)
);

