<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>grocery-back-office-api</AssemblyName>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Dapper.FSharp" Version="4.9.0" />
    <PackageReference Include="dotnetenv" Version="3.1.1" />
    <PackageReference Include="Giraffe" Version="6.4.0" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Configs.fs" />
    <Compile Include="src/Infrastructure/Core/Types/*.fs" />
    <Compile Include="src/Core/Interfaces/IValidationRule.fs" />
    <Compile Include="src/Core/Interfaces/IValidatable.fs" />
    <Compile Include="src/Core/Exceptions/**/*.fs" />
    <Compile Include="src/Helpers/**/*.fs" />

    <Compile Include="src/Infrastructure/Core/Exceptions/*.fs" />
    <Compile Include="src/Infrastructure/Core/Implementations/*.fs" />
    <Compile Include="src/Infrastructure/Core/*.fs" />

    <Compile Include="src/Core/Enums/**/*.fs" />
    <Compile Include="src/Core/Entities/TimeSlot.fs" />
    <Compile Include="src/Core/Entities/**/*.fs" Exclude="src/Core/Entities/TimeSlot.fs" />

    <Compile Include="src/Core/ValidationRules/**/*.fs" />
    <Compile Include="src/Core/Jobs/**/*.fs" />
    <Compile Include="src/Core/Events/**/*.fs" />

    <Compile Include="src/App/Interfaces/**/*.fs" />
    <Compile Include="src/Infrastructure/Repositories/**/*.fs" />
    <Compile Include="src/App/Repositories/**/*.fs" />

    <Compile Include="src/App/Services/AuthService.fs" />
    <Compile Include="src/App/Services/UserService.fs" />
    <Compile Include="src/App/Services/CustomerService.fs" />
    <Compile Include="src/App/Services/WeekdayService.fs" />
    <Compile Include="src/App/Services/DeliveryTimeRuleService.fs" />
    <Compile Include="src/App/Services/ProductStorageTypeService.fs" />
    <Compile Include="src/App/Services/ProductService.fs" />
    <Compile Include="src/App/Services/OrderItemService.fs" />
    <Compile Include="src/App/Services/OrderService.fs" />
    <Compile Include="src/App/Services/DeliveryTimeService.fs" />

    <Compile Include="src/Http/Resources/**/*Resource.fs" />
    <Compile Include="src/Http/Resources/**/*Collection.fs" />
    <Compile Include="src/Http/Requests/**/*.fs" />
    <Compile
        Include="src/Http/**/*.fs"
        Exclude="src/Http/Re*/**/*.fs"
    />

    <Compile Include="src/Core/ErrorHandlers/**/*.fs" />

    <Compile Include="Program.fs" />

    <Compile Remove="./assets/*" />
    <Compile Remove="./src/Infrastructure/Scripts/*.fs" />
    <Compile Remove="./src/Infrastructure/Scripts/*.fsx" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="./assets/*" />
    <Content Include="./assets/*" Watch="false" />
  </ItemGroup>

  <ItemGroup>
    <None Include="web.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
