CREATE TABLE products (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    description TEXT,
    product_storage_type_id INT NOT NULL REFERENCES product_storage_types(id)
);

