CREATE TABLE delivery_time_rule_not_available_weekdays (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    delivery_time_rule_id INT NOT NULL REFERENCES delivery_time_rules(id) ON DELETE CASCADE ON UPDATE CASCADE,
    weekday_id INT NOT NULL REFERENCES weekdays(id) ON DELETE CASCADE ON UPDATE CASCADE
);

