CREATE TABLE delivery_time_rule_not_available_weekdays (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    delivery_time_rule_id INT NOT NULL REFERENCES delivery_time_rule(id),
    weekday_id INT NOT NULL REFERENCES weekday(id)
);

